--- #YAML:1.0
name:               Text-Extract-Word
version:            0.01
abstract:           Extract text from Word files
author:
    - Stuart Watt <stuart@morungos.com>
license:            artistic
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Encode:             0
    IO::File:           0
    OLE::Storage_Lite:  0
    perl:               5.008000
    POSIX:              0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
